apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: react-docker
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  - name: backend
    port: 3059
    targetPort: 3059
    protocol: TCP
  selector:
    app: react-docker
