apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: react-docker
spec:
  type: LoadBalancer
  ports:
  # This is the port that application can be accessed on:
  - port: 8080
  # This seems needs to point to containerPort for the pod:
    targetPort: 80
    protocol: TCP
  # This is port for outside cluster, but does not seem to be doing anything!
    nodePort: 31000
  selector:
    app: react-docker
